### ISSUE TITLE
Initial plugin design

### ISSUE THREAD

**Issue by simonw** [datasette/datasette-queries#1]
Goal of this plugin is to replace https://github.com/simonw/datasette-saved-queries with a modern and much improved version.

- Nicer UI
- Can handle writable canned queries as well (in later version)

**TODO for first alpha**

- [x] Refactor HTML/CSS/JavaScript out into a template
- [x] Add some tests
- [x] Think about how configuration and permissions could work

**TODO next**

- [x] Code to ensure slug doesn't clash with an existing table or view
- [x] Make `datasette-llm-usage` dependency optional
- [x] Ability to delete a saved query (I may skip "edit")
- [x] Think about how this could work with models other than `gpt-4o-mini`

**Future features**

- Writable canned query
- Edit query
- Revision history of edited queries (makes it much more collaborative)

**Comment by TechSolomon** [comment]
### datasette, version 0.65.1

```zsh
error: uninstall-no-record-file

× Cannot uninstall datasette 0.65.1
╰─> The package's contents are unknown: no RECORD file was found for datasette.
```

**Comment by simonw** [comment]
Attempting to save a query with an existing query URL currently fails with this 500 error:

<img width="1314" height="296" alt="Image" src="https://github.com/user-attachments/assets/f3dafe8f-3e8a-4d3e-838f-e4af9ac94f32" />

**Comment by simonw** [comment]
Since I haven't shipped `catalog_views` in a Datasette release yet I'm going to use the documented introspection methods instead: https://docs.datasette.io/en/stable/internals.html#database-introspection
